name: Deploy Lambda Function with API Gateway

on:
  push:
    branches: [ main ]  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Checkout the repository code

      - name: Install zip tool
        uses: montudor/action-zip@v1  # Install zip tool

      - name: Create Zip file for Lambda function
        run: zip -r code.zip .  # Package the Lambda function code

      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest  # Set up AWS CLI
        with:
          args: |
            # Update Lambda function with the ZIP file
            aws lambda update-function-code \
              --function-name arn:aws:lambda:ap-south-1:899920141210:function:fastapi-onboarding \
              --zip-file fileb://code.zip

            # Create the API Gateway (if not already created)
            api_id=$(aws apigateway create-rest-api \
              --name "FastAPI-Onboarding-API" \
              --region ${{ secrets.AWS_REGION }} \
              --query 'id' \
              --output text)

            # Create the root resource
            root_resource_id=$(aws apigateway get-resources \
              --rest-api-id $api_id \
              --query 'items[?path==`/`].id' \
              --output text)

            # Create a new POST method
            aws apigateway put-method \
              --rest-api-id $api_id \
              --resource-id $root_resource_id \
              --http-method POST \
              --authorization-type NONE

            # Set up the Lambda integration for the POST method
            aws apigateway put-integration \
              --rest-api-id $api_id \
              --resource-id $root_resource_id \
              --http-method POST \
              --integration-http-method POST \
              --type AWS_PROXY \
              --uri arn:aws:apigateway:${{ secrets.AWS_REGION }}:lambda:path/2015-03-31/functions/arn:aws:lambda:${{ secrets.AWS_REGION }}:899920141210:function:fastapi-onboarding/invocations

            # Grant API Gateway permission to invoke Lambda
            aws lambda add-permission \
              --function-name fastapi-onboarding \
              --principal apigateway.amazonaws.com \
              --statement-id $(date +%s) \
              --action lambda:InvokeFunction

            # Deploy the API Gateway
            aws apigateway create-deployment \
              --rest-api-id $api_id \
              --stage-name prod

            # Output the API Gateway URL
            api_url="https://${api_id}.execute-api.${{ secrets.AWS_REGION }}.amazonaws.com/prod/"
            echo "API Gateway URL: $api_url"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
